//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallCenterEntities : DbContext
    {
        public CallCenterEntities()
            : base("name=CallCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addreses> Addreses { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<IntercoCompanies> IntercoCompanies { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<SOSW> SOSW { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
