//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOSW
    {
        public int ID { get; set; }
        public System.DateTime CallDate { get; set; }
        public string ResultCall { get; set; }
        public decimal TotalPrice { get; set; }
        public string Review { get; set; }
        public int IDApplication { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
